# Generated by Django 4.1.7 on 2023-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('rtime', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
                ('companyemail', models.CharField(max_length=40)),
                ('companymobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Retailer',
            },
        ),
    ]
